/* Imágenes de las tarjetas: «baraja|anverso» → media/tarjetas/<nombre>.webp.
   Si una tarjeta no está aquí, se queda con su icono. Las imágenes no se precachean: se cargan al mostrarlas.
   GENERADO por tools/generar_tarjetas_img.py desde recursos/tarjetas_prompts/*.json: no editar a mano. */
const TARJETAS_IMG = {
 "kant|A priori": "a_priori",
 "platon|Mundo inteligible": "mundo_inteligible",
 "platon|Mundu adigarria": "mundo_inteligible",
 "ipc-falacias|Hombre de paja": "hombre_de_paja",
 "ipc-falacias|Lastozko gizona": "hombre_de_paja",
 "ipc-falacias|稻草人": "hombre_de_paja",
 "existencialismo|Mala fe": "mala_fe",
 "existencialismo|Fede txarra": "mala_fe",
 "siglo21|Modernidad líquida": "modernidad_liquida",
 "siglo21|Modernitate likidoa": "modernidad_liquida",
 "fil-posverdad|Cámara de eco": "camara_de_eco",
 "fil-posverdad|Oihartzun-ganbera": "camara_de_eco",
 "historicidad|Historicidad": "historicidad",
 "historicidad|Historikotasuna": "historicidad",
 "historicidad|Universalidad": "universalidad",
 "historicidad|Unibertsaltasuna": "universalidad",
 "historicidad|Canon": "canon",
 "historicidad|Kanona": "canon",
 "historicidad|Transmisión": "transmision",
 "historicidad|Transmisioa": "transmision",
 "metodos|Argumento": "argumento",
 "metodos|Argudioa": "argumento",
 "metodos|论证": "argumento",
 "fil-metodo|Argumento": "argumento",
 "fil-metodo|Argudioa": "argumento",
 "fil-metodo|论证": "argumento",
 "ipc-conceptos|Argumento": "argumento",
 "ipc-conceptos|Argudioa": "argumento",
 "ipc-conceptos|论证": "argumento",
 "metodos|Falacia": "falacia",
 "metodos|Faltsukeria": "falacia",
 "metodos|谬误": "falacia",
 "metodos|Principio de caridad": "principio_de_caridad",
 "metodos|Karitate-printzipioa": "principio_de_caridad",
 "metodos|善意原则": "principio_de_caridad",
 "metodos|Método filosófico": "metodo_filosofico",
 "metodos|Metodo filosofikoa": "metodo_filosofico",
 "metodos|Género filosófico": "genero_filosofico",
 "metodos|Genero filosofikoa": "genero_filosofico",
 "mito|¿Quién explica el mundo?": "quien_explica_el_mundo",
 "mito|Nork azaltzen du mundua?": "quien_explica_el_mundo",
 "mito|¿Cómo se transmite?": "como_se_transmite",
 "mito|Nola transmititzen da?": "como_se_transmite",
 "mito|¿Se puede discutir?": "se_puede_discutir",
 "mito|Eztabaida al daiteke?": "se_puede_discutir",
 "mito|physis": "physis",
 "mito|arché": "arche",
 "mito|arkhe": "arche",
 "mito|Necesidad (ananké)": "ananke",
 "mito|Beharrezkotasuna (ananke)": "ananke",
 "aporias|Antropomorfismo": "antropomorfismo",
 "aporias|Antropomorfismoa": "antropomorfismo",
 "aporias|Regreso infinito de causas": "regreso_infinito",
 "aporias|Kausen erregresio infinitua": "regreso_infinito",
 "aporias|Lo uno y lo múltiple": "uno_y_multiple",
 "aporias|Bata eta anitza": "uno_y_multiple",
 "aporias|Lo general y lo singular": "general_y_singular",
 "aporias|Orokorra eta singularra": "general_y_singular",
 "aporias|Naturaleza y convención": "naturaleza_y_convencion",
 "aporias|Natura eta konbentzioa": "naturaleza_y_convencion",
 "sofistas|physis / nomos": "naturaleza_y_convencion",
 "aporias|El cambio y la permanencia": "cambio_y_permanencia",
 "aporias|Aldaketa eta iraupena": "cambio_y_permanencia",
 "aporias|El movimiento (Zenón)": "movimiento_zenon",
 "aporias|Mugimendua (Zenon)": "movimiento_zenon",
 "aporias|Purificación del alma": "purificacion_del_alma",
 "aporias|Arimaren purifikazioa": "purificacion_del_alma",
 "aporias|Sentidos y razón": "sentidos_y_razon",
 "aporias|Zentzumenak eta arrazoia": "sentidos_y_razon",
 "aporias|La identidad personal": "identidad_personal",
 "aporias|Identitate pertsonala": "identidad_personal",
 "fil-identidad|Identidad personal": "identidad_personal",
 "fil-identidad|Nortasun pertsonala": "identidad_personal",
 "aporias|Las preguntas como motor": "preguntas_como_motor",
 "aporias|Galderak motor gisa": "preguntas_como_motor",
 "sofistas|La Ilustración griega": "ilustracion_griega",
 "sofistas|Ilustrazio greziarra": "ilustracion_griega",
 "sofistas|Los sofistas": "los_sofistas",
 "sofistas|Sofistak": "los_sofistas",
 "sofistas|Protágoras": "protagoras",
 "sofistas|Protagoras": "protagoras",
 "sofistas|Gorgias": "gorgias",
 "sofistas|Hipias": "hipias",
 "sofistas|Sócrates": "socrates",
 "sofistas|Sokrates": "socrates",
 "sofistas|苏格拉底": "socrates",
 "sofistas|Ironía y mayéutica": "ironia_y_mayeutica",
 "sofistas|Ironia eta maieutika": "ironia_y_mayeutica",
 "antropologia|Mayéutica": "ironia_y_mayeutica",
 "antropologia|Maieutika": "ironia_y_mayeutica",
 "sofistas|Aspasia de Mileto": "aspasia",
 "sofistas|Aspasia Miletokoa": "aspasia",
 "sofistas|Cobrar por enseñar": "cobrar_por_ensenar",
 "sofistas|Irakasteagatik kobratzea": "cobrar_por_ensenar",
 "sofistas|A quién enseñan": "a_quien_ensenan",
 "sofistas|Nori irakasten dioten": "a_quien_ensenan",
 "sofistas|Qué enseñan": "que_ensenan",
 "sofistas|Zer irakasten duten": "que_ensenan",
 "sofistas|Cómo viven": "como_viven",
 "sofistas|Nola bizi diren": "como_viven",
 "sofistas|Intelectualismo moral": "intelectualismo_moral",
 "sofistas|Intelektualismo morala": "intelectualismo_moral",
 "antropologia|Intelectualismo moral": "intelectualismo_moral",
 "antropologia|Intelektualismo morala": "intelectualismo_moral",
 "etica|Intelectualismo moral": "intelectualismo_moral",
 "etica|Intelektualismo morala": "intelectualismo_moral",
 "sofistas|Docta ignorancia": "docta_ignorancia",
 "sofistas|Ezjakintasun jakintsua": "docta_ignorancia",
 "sofistas|Jenofonte": "jenofonte",
 "sofistas|Xenofonte": "jenofonte",
 "platon|Idea (Forma)": "idea_forma",
 "platon|Ideia (Forma)": "idea_forma",
 "platon|Mundo sensible": "mundo_sensible",
 "platon|Mundu sentikorra": "mundo_sensible",
 "platon|Doxa": "doxa",
 "platon|Episteme": "episteme",
 "platon|Dialéctica": "dialectica",
 "platon|Dialektika": "dialectica",
 "platon|Reminiscencia (anamnesis)": "reminiscencia",
 "platon|Oroitzapena (anamnesis)": "reminiscencia",
 "antropologia|Reminiscencia": "reminiscencia",
 "antropologia|Oroitzapena": "reminiscencia",
 "platon|Paideia": "paideia",
 "platon|Dualismo ontológico": "dualismo_ontologico",
 "platon|Dualismo ontologikoa": "dualismo_ontologico",
 "platon|Dualismo antropológico": "dualismo_antropologico",
 "platon|Dualismo antropologikoa": "dualismo_antropologico",
 "antropologia|Dualismo": "dualismo_antropologico",
 "antropologia|Dualismoa": "dualismo_antropologico",
 "metafisica|Dualismo": "dualismo_antropologico",
 "metafisica|Dualismoa": "dualismo_antropologico",
 "fil-mente|Dualismo": "dualismo_antropologico",
 "fil-mente|Dualismoa": "dualismo_antropologico",
 "platon|Rey filósofo": "rey_filosofo",
 "platon|Errege filosofoa": "rey_filosofo",
 "politica|Rey filósofo": "rey_filosofo",
 "politica|Errege filosofoa": "rey_filosofo",
 "platon|Demiurgo": "demiurgo",
 "platon|Demiurgoa": "demiurgo",
 "platon|Del caos al cosmos": "del_caos_al_cosmos",
 "platon|Kaosetik kosmosera": "del_caos_al_cosmos",
 "platon|Alma del mundo": "alma_del_mundo",
 "platon|Munduaren arima": "alma_del_mundo",
 "platon|Visión teleológica": "vision_teleologica",
 "platon|Ikuspegi teleologikoa": "vision_teleologica",
 "platon|Un mundo matemático": "mundo_matematico",
 "platon|Mundu matematiko bat": "mundo_matematico",
 "platon|Cosmogonía: un relato verosímil": "cosmogonia_relato",
 "platon|Kosmogonia: egiantzeko kontakizuna": "cosmogonia_relato",
 "platon|Aristóteles frente a Platón": "aristoteles_frente_a_platon",
 "platon|Aristoteles Platonen aurrean": "aristoteles_frente_a_platon",
 "antropologia|Psique": "psique",
 "antropologia|Psikea": "psique",
 "antropologia|Giro antropológico": "giro_antropologico",
 "antropologia|Bira antropologikoa": "giro_antropologico",
 "antropologia|Hilemorfismo": "hilemorfismo",
 "antropologia|Hilemorfismoa": "hilemorfismo",
 "antropologia|Metempsicosis": "metempsicosis",
 "antropologia|Metenpsikosia": "metempsicosis",
 "antropologia|Acto y potencia": "acto_y_potencia",
 "antropologia|Aktua eta potentzia": "acto_y_potencia",
 "antropologia|Las cuatro causas": "cuatro_causas",
 "antropologia|Lau kausak": "cuatro_causas",
 "antropologia|Motor inmóvil": "motor_inmovil",
 "antropologia|Motor geldia": "motor_inmovil",
 "etica|Ética": "etica",
 "etica|Etika": "etica",
 "etica|Areté": "arete",
 "etica|Arete": "arete",
 "etica|Eudaimonía": "eudaimonia",
 "etica|Eudaimonia": "eudaimonia",
 "etica|Virtudes dianoéticas": "virtudes_dianoeticas",
 "etica|Bertute dianoetikoak": "virtudes_dianoeticas",
 "etica|Virtudes éticas": "virtudes_eticas",
 "etica|Bertute etikoak": "virtudes_eticas",
 "etica|Término medio": "termino_medio",
 "etica|Termino erdikoa": "termino_medio",
 "etica|Prudencia": "prudencia",
 "etica|Zuhurtzia": "prudencia",
 "politica|Polis": "polis",
 "politica|Polis-a": "polis",
 "politica|Utopía": "utopia",
 "politica|Utopia": "utopia",
 "politica|Zoon politikón": "zoon_politikon",
 "politica|Zoon politikon": "zoon_politikon",
 "politica|Monarquía": "monarquia",
 "politica|Monarkia": "monarquia",
 "politica|Aristocracia": "aristocracia",
 "politica|Aristokrazia": "aristocracia",
 "politica|República": "republica",
 "politica|Errepublika": "republica",
 "politica|Tiranía": "tirania",
 "politica|Tirania": "tirania",
 "politica|Demagogia": "demagogia",
 "politica|Ostracismo": "ostracismo",
 "politica|Ostrakismoa": "ostracismo",
 "politica|Clase media": "clase_media",
 "politica|Klase ertaina": "clase_media",
 "helenismo|Helenismo": "helenismo",
 "helenismo|Helenismoa": "helenismo",
 "helenismo|Autarquía": "autarquia",
 "helenismo|Autarkia": "autarquia",
 "helenismo|Logos": "logos_estoico",
 "helenismo|Logosa": "logos_estoico",
 "helenismo|Apatía": "apatia",
 "helenismo|Apatia": "apatia",
 "helenismo|Ataraxia": "ataraxia",
 "helenismo|Aponía": "aponia",
 "helenismo|Aponia": "aponia",
 "helenismo|Tetrafármaco": "tetrafarmaco",
 "helenismo|Tetrafarmakoa": "tetrafarmaco",
 "fil-helenismo|El tetrafármaco": "tetrafarmaco",
 "fil-helenismo|Tetrafarmakoa": "tetrafarmaco",
 "helenismo|Epojé": "epoje",
 "helenismo|Epokhe": "epoje",
 "helenismo|Cosmopolitismo": "cosmopolitismo",
 "helenismo|Kosmopolitismoa": "cosmopolitismo",
 "helenismo|Lathe biosas": "lathe_biosas",
 "helenismo|Koiné": "koine",
 "helenismo|Koine": "koine",
 "medieval|Patrística": "patristica",
 "medieval|Patristika": "patristica",
 "medieval|Escolástica": "escolastica",
 "medieval|Eskolastika": "escolastica",
 "medieval|Universales": "universales",
 "medieval|Unibertsalak": "universales",
 "medieval|Nominalismo": "nominalismo",
 "medieval|Nominalismoa": "nominalismo",
 "medieval|Microcosmos": "microcosmos",
 "medieval|Mikrokosmosa": "microcosmos",
 "medieval|Macrocosmos": "macrocosmos",
 "medieval|Makrokosmosa": "macrocosmos",
 "medieval|Neoplatonismo": "neoplatonismo",
 "medieval|Neoplatonismoa": "neoplatonismo",
 "medieval|Conversión": "conversion",
 "medieval|Konbertsioa": "conversion",
 "medieval|Interioridad": "interioridad",
 "medieval|Barrentasuna": "interioridad",
 "feRazon|Creación": "creacion",
 "feRazon|Kreazioa": "creacion",
 "feRazon|Emanación": "emanacion",
 "feRazon|Emanazioa": "emanacion",
 "feRazon|Iluminación": "iluminacion",
 "feRazon|Iluminazioa": "iluminacion",
 "feRazon|Cinco vías": "cinco_vias",
 "feRazon|Bost bideak": "cinco_vias",
 "feRazon|Navaja de Ockham": "navaja_de_ockham",
 "feRazon|Ockhamen labana": "navaja_de_ockham",
 "feRazon|Verdad sobrenatural": "verdad_sobrenatural",
 "feRazon|Egia naturaz gaindikoa": "verdad_sobrenatural",
 "feRazon|Verdad natural": "verdad_natural",
 "feRazon|Egia naturala": "verdad_natural",
 "feRazon|Ley natural": "ley_natural",
 "feRazon|Lege naturala": "ley_natural",
 "feRazon|Trivium y quadrivium": "trivium_quadrivium",
 "feRazon|Trivium eta quadrivium": "trivium_quadrivium",
 "modernidad|Humanismo": "humanismo",
 "modernidad|Humanismoa": "humanismo",
 "modernidad|Antropocentrismo": "antropocentrismo",
 "modernidad|Antropozentrismoa": "antropocentrismo",
 "modernidad|Heliocentrismo": "heliocentrismo",
 "modernidad|Heliozentrismoa": "heliocentrismo",
 "modernidad|Mecanicismo": "mecanicismo",
 "modernidad|Mekanizismoa": "mecanicismo",
 "modernidad|Positivismo": "positivismo",
 "modernidad|Positibismoa": "positivismo",
 "modernidad|Secularización": "secularizacion",
 "modernidad|Sekularizazioa": "secularizacion",
 "modernidad|Dignitas hominis": "dignitas_hominis",
 "modernidad|Virtù": "virtu",
 "metafisica|Sustancia": "sustancia",
 "metafisica|Substantzia": "sustancia",
 "metafisica|Res cogitans": "res_cogitans",
 "metafisica|Res extensa": "res_extensa",
 "metafisica|Materialismo": "materialismo",
 "metafisica|Materialismoa": "materialismo",
 "metafisica|Determinismo": "determinismo",
 "metafisica|Determinismoa": "determinismo",
 "metafisica|Hombre-máquina": "hombre_maquina",
 "metafisica|Gizaki-makina": "hombre_maquina",
 "metafisica|Mónadas": "monadas",
 "metafisica|Monadak": "monadas",
 "metafisica|Ocasionalismo": "ocasionalismo",
 "metafisica|Okasionalismoa": "ocasionalismo",
 "contrato|Contrato social": "contrato_social",
 "contrato|Kontratu soziala": "contrato_social",
 "fil-politica|El contrato social": "contrato_social",
 "fil-politica|Gizarte-kontratua": "contrato_social",
 "contrato|Estado de naturaleza": "estado_de_naturaleza",
 "contrato|Naturazko egoera": "estado_de_naturaleza",
 "contrato|Leviatán": "leviatan",
 "contrato|Leviatan": "leviatan",
 "fil-politica|Hobbes y el Leviatán": "leviatan",
 "fil-politica|Hobbes eta Leviatana": "leviatan",
 "contrato|Derechos naturales": "derechos_naturales",
 "contrato|Eskubide naturalak": "derechos_naturales",
 "ilustracion|Derechos naturales": "derechos_naturales",
 "ilustracion|Eskubide naturalak": "derechos_naturales",
 "contrato|Voluntad general": "voluntad_general",
 "contrato|Borondate orokorra": "voluntad_general",
 "contrato|Estado de derecho": "estado_de_derecho",
 "contrato|Zuzenbide-estatua": "estado_de_derecho",
 "contrato|Coerción": "coercion",
 "contrato|Hertsapena": "coercion",
 "utilitarismo|Liberalismo": "liberalismo",
 "utilitarismo|Liberalismoa": "liberalismo",
 "utilitarismo|Utilitarismo": "utilitarismo",
 "utilitarismo|Utilitarismoa": "utilitarismo",
 "utilitarismo|功利主义": "utilitarismo",
 "utilitarismo|Principio de la mayor felicidad": "mayor_felicidad",
 "utilitarismo|Zoriontasun handienaren printzipioa": "mayor_felicidad",
 "eticaDeber|Principio de utilidad": "mayor_felicidad",
 "eticaDeber|Baliagarritasunaren printzipioa": "mayor_felicidad",
 "utilitarismo|Mano invisible": "mano_invisible",
 "utilitarismo|Esku ikusezina": "mano_invisible",
 "utilitarismo|Propiedad privada": "propiedad_privada",
 "utilitarismo|Jabetza pribatua": "propiedad_privada",
 "utilitarismo|Darwinismo social": "darwinismo_social",
 "utilitarismo|Sozialdarwinismoa": "darwinismo_social",
 "utilitarismo|Cooperación": "cooperacion",
 "utilitarismo|Lankidetza": "cooperacion",
 "utilitarismo|合作": "cooperacion"
};
